# Generated by Django 3.2.9 on 2021-12-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Class Blog', max_length=255),
        ),
    ]
